# Generated by Django 4.0.2 on 2022-02-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['username', 'registred', 'phone_number'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='auth_key',
        ),
    ]
